contrail_nodes:
kube_api_vip:
vrouter_physical_interface:
contrail_registry:
contrail_container_tag:

#!/usr/bin/env bash
export contrail_nodes=${contrail_nodes}
export kube_api_vip=${kube_api_vip}
export contrail_registry=${contrail_registry}
export contrail_container_tag=${contrail_container_tag}
export vrouter_physical_interface=${vrouter_physical_interface}
for f in contrail/*.yml
do
 envsubst < $f > “.generated/$(basename $f)”
done
