---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analyticsdb
  namespace: kube-system
  labels:
    app: contrail-analyticsdb
spec:
  template:
    metadata:
      labels:
        app: contrail-analyticsdb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "opencontrail.org/controller"
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-analyticsdb
        image: "ci-repo.englab.juniper.net:5000/contrail-external-cassandra:5.0-51"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: contrail-analyticsdb-config
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: analyticsdb-data
        - mountPath: /var/log/cassandra
          name: analyticsdb-log
      volumes:
      - name: analyticsdb-data
        hostPath:
          path: /var/lib/contrail/analyticsdb
      - name: analyticsdb-log
        hostPath:
          path: /var/log/contrail/analyticsdb
      - name: kafka
        image: "ci-repo.englab.juniper.net:5000/contrail-external-kafka:5.0-51"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: contrail-analytics-zookeeper
        volumeMounts:
        - mountPath: /tmp/kafka-logs
          name: kafka-logs
      volumes:
      - name: kafka-logs
        hostPath:
          path: /var/lib/contrail/kafka-logs
      - name: zookeeper
        image: "ci-repo.englab.juniper.net:5000/contrail-external-zookeeper:5.0-51"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: contrail-analytics-zookeeper
        volumeMounts:
        - mountPath: /var/lib/zookeeper
          name: zookeeper-data
        - mountPath: /var/log/zookeeper
          name: zookeeper-logs
        volumeMounts:
        - mountPath: /data
          name: analytics-zookeeper-data
        - mountPath: /datalog
          name: analytics-zookeeper-datalog
      volumes:
      - name: analytics-zookeeper-data
        hostPath:
          path: /var/lib/analytics_zookeeper_data
      - name: analytics-zookeeper-datalog
        hostPath:
          path: /var/lib/analytics_zookeeper_datalog
      - name: contrail-analytics-nodemgr
        image: "ci-repo.englab.juniper.net:5000/contrail-nodemgr:5.0-51"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: nodemgr-config
        - configMapRef:
            name: contrail-analytics-zookeeper
        env:
        - name: NODE_TYPE
          value: analyticsdb
