apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: kube-system
data:
  AAA_MODE: no-auth 
  ANALYTICS_NODES: 10.0.2.15 
  ANALYTICSDB_NODES: 10.0.2.15 
  AUTH_MODE: noauth
  CLOUD_ORCHESTRATOR: kubernetes
  CONFIG_NODES: 10.0.2.15 
  CONFIGDB_NODES: 10.0.2.15 
  CONTROL_NODES: 10.0.2.15 
  CONTROLLER_NODES: 10.0.2.15 
  KAFKA_NODES: 10.0.2.15 
  LOG_LEVEL: SYS_LOG
  METADATA_PROXY_SECRET: contrail
  PHYSICAL_INTERFACE: eth0 
  RABBITMQ_NODES: 10.0.2.15 
  RABBITMQ_NODE_PORT: "5672"
  REDIS_NODES: 10.0.2.15 
  WEBUI_NODES: 10.0.2.15 
  ZOOKEEPER_NODES: 10.0.2.15 
  KUBERNETES_API_SECURE_PORT: "6443"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodemgr-config
  namespace: kube-system
data:
  DOCKER_HOST: "unix://mnt/docker.sock"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-analyticsdb-config
  namespace: kube-system
data:
  CASSANDRA_SEEDS: 10.0.2.15
  CASSANDRA_CLUSTER_NAME: Contrail
  CASSANDRA_START_RPC: "true"
  CASSANDRA_LISTEN_ADDRESS: auto
  CASSANDRA_PORT: "9160"
  CASSANDRA_CQL_PORT: "9042"
  CASSANDRA_SSL_STORAGE_PORT: "7001"
  CASSANDRA_STORAGE_PORT: "7000"
  CASSANDRA_JMX_LOCAL_PORT: "7200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-configdb-config
  namespace: kube-system
data:
  CASSANDRA_SEEDS: 10.0.2.15 
  CASSANDRA_CLUSTER_NAME: ContrailConfigDB
  CASSANDRA_START_RPC: "true"
  CASSANDRA_LISTEN_ADDRESS: auto
  CASSANDRA_PORT: "9161"
  CASSANDRA_CQL_PORT: "9041"
  CASSANDRA_SSL_STORAGE_PORT: "7011"
  CASSANDRA_STORAGE_PORT: "7010"
  CASSANDRA_JMX_LOCAL_PORT: "7201"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: kube-system
data:
  RABBITMQ_NODES: 10.0.2.15 
  RABBITMQ_NODE_PORT: "5672"
  RABBITMQ_ERLANG_COOKIE: "47EFF3BB-4786-46E0-A5BB-58455B3C2CB4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-config-zookeeper
  namespace: kube-system
data:
  ZOOKEEPER_PORT: "2181"
  ZOOKEEPER_PORTS: "2888:3888"
  ZOOKEEPER_NODES: 10.0.2.15 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-analytics-zookeeper
  namespace: kube-system
data:
  ZOOKEEPER_PORT: "2182"
  ZOOKEEPER_PORTS: "4888:5888"
  ZOOKEEPER_NODES: 10.0.2.15 
# Containers section

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-manager-config
  namespace: kube-system
data:
  KUBERNETES_API_SERVER: 10.0.2.15 
  KUBERNETES_API_SECURE_PORT: "6443"
  K8S_TOKEN_FILE: "/tmp/serviceaccount/token"
# Containers section
# Meta information section
