---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail
  namespace: kube-system
---
kind: ClusterRole
apiVersion: v1
metadata:
  name: contrail
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: contrail
roleRef:
  name: contrail
subjects:
- kind: SystemUser
  name: kube-system:contrail
- kind: ServiceAccount
  name: contrail
  namespace: kube-system
userNames:
  - system:serviceaccount:kube-system:contrail
---
apiVersion: v1
kind: Secret
metadata:
  name: contrail-kube-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: contrail
type: kubernetes.io/service-account-token
---
